---
title: "Figure 2 tables"
output: html_document
---

Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = normalizePath("../../../"))
```

```{r}
# Load libraries
library(ggplot2)
library(gridExtra)
library(ggrepel)
library(ggpubr)
library(dplyr)
library(tidyr)
library(reshape2)

if(!exists("snakemake")){
  setwd("../../..")
  source("scripts/util/paper/parse_snakemake.R")
  parse_snakemake(rule = "figure_2_statistics_other_classifiers")
}

#setwd("/hpcdata/sg/sg_data/PROJECTS/Monogenic_Project")

# Source utilities
source('scripts/util/Plotting/plot_auc.R')
source('scripts/util/paper/abbrev_cond.R')

RF.META.IN.PATHS = list(
  CGD = snakemake@input[["cgd_meta"]],#'Classification/cgd_random_forest_sample_meta_data_all.RDS',
  STAT1.GOF = snakemake@input[["stat1_meta"]],#'Classification/stat1_random_forest_sample_meta_data_all.RDS',
  FMF = snakemake@input[["fmf_meta"]],#'Classification/fmf_random_forest_sample_meta_data_all.RDS',
  Job = snakemake@input[["job_meta"]]#'Classification/job_random_forest_sample_meta_data_all.RDS'
)


## The LOO CV results for each patient for each condition-based random forest classifier
HI.CONDITION.IN.PATHS = list(
  CGD = snakemake@input[["cgd_res"]],#'Classification/results/cgd_rf_results_all.RDS',
  STAT1.GOF = snakemake@input[["stat1_res"]],#'Classification/results/stat1_rf_results_all.RDS',
  FMF = snakemake@input[["fmf_res"]],#'Classification/results/fmf_rf_results_all.RDS',
  Job = snakemake@input[["job_res"]]#'Classification/results/job_rf_results_all.RDS'
)

# Supplemental Figure 4f -- condition-specific classifiers
results = lapply(HI.CONDITION.IN.PATHS, readRDS) ## Extract the condition-specific classifier results 


metas = lapply(RF.META.IN.PATHS, readRDS) ## Extact the meta data assocaited with each condition-specific classifier

## List the condition groups for each classifier
condition.groups = list(CGD = c('XCGD', '47CGD'),
                        STAT1.GOF = 'STAT1 GOF',
                        FMF = 'FMF',
                        Job = 'Job')

## Create a name conversion map to make the data types underlying each classifier more clear
conversion = c("microarray.modules" = 'Gene modules', 
               "tbnks" = 'CBCs + Lymphocyte Phenotyping',
               "cbcs" = 'CBCs',
               "somalogic.modules" = 'Protein modules', 
               "all.modules.with.tbnks" = 'Modules + CBCs', 
               "all.modules.plus.grey.with.tbnks" = 'Modules + CBCs + Grey Proteins')

## Insantiate a function to get the AUC associated with each classifier and each condition
get_aucs = function(result, meta, condition.group) {
  ## Get the condition associated with each patient
  conditions = meta[rownames(result), 'condition']
  apply(result, 2, function(x) {
    ## Get the ROC curve associated with each classifier
    roc = get_roc(x = x, y = conditions, pos = condition.group)
    ## Get the AUC of that ROC curve
    get_auc(roc)
  })
}

## Run the function on each of the condition-specific classifier results (and simplify into a matrix)
aucs = mapply(get_aucs, results, metas, condition.groups, SIMPLIFY = T)

## Create a data frame holding the AUCs for each classifier, and melt it
df = as.data.frame(aucs) %>% 
  tibble::rownames_to_column(var = 'classifier') %>%
  mutate(classifier = conversion[classifier]) %>%
  mutate(classifier = factor(classifier, levels = conversion)) %>%
  melt()

df <- df %>%
        filter(grepl("Grey", classifier))

```

# AUCs for each condition
```{r}
print("AUCs")
print(df)

```


# N in each class

### N CGD
```{r}
table(metas$CGD$condition %in% c("XCGD", "47CGD"))
```


### N STAT1 
```{r}
table(metas$STAT1.GOF$condition == "STAT1 GOF")
```

### N FMF 
```{r}
table(metas$FMF$condition == "FMF")
```

### N Job
```{r}
table(metas$Job$condition == "Job")
```
